///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace OnlineTutorial
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AddEntry recording.
    /// </summary>
    [TestModule("cc35cb22-c8e2-49dc-ad2a-22efbdc9885c", ModuleType.Recording, 1)]
    public partial class AddEntry : ITestModule
    {
        /// <summary>
        /// Holds an instance of the OnlineTutorialRepository repository.
        /// </summary>
        public static OnlineTutorialRepository repo = OnlineTutorialRepository.Instance;

        static AddEntry instance = new AddEntry();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddEntry()
        {
            varTitle = "WorldPressDemo";
            varUsername = "admin";
            varPassword = "demo123";
            varUrl = "http://bitly.com/wp_demo";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddEntry Instance
        {
            get { return instance; }
        }

#region Variables

        string _varUsername;

        /// <summary>
        /// Gets or sets the value of variable varUsername.
        /// </summary>
        [TestVariable("1f45f33a-212a-4bfb-a5f3-671c78a89db7")]
        public string varUsername
        {
            get { return _varUsername; }
            set { _varUsername = value; }
        }

        string _varPassword;

        /// <summary>
        /// Gets or sets the value of variable varPassword.
        /// </summary>
        [TestVariable("1683cb0f-0361-4cfc-ac5a-90dd8fcba8fc")]
        public string varPassword
        {
            get { return _varPassword; }
            set { _varPassword = value; }
        }

        string _varUrl;

        /// <summary>
        /// Gets or sets the value of variable varUrl.
        /// </summary>
        [TestVariable("ccb2f901-1251-4036-9331-dded2fedbab3")]
        public string varUrl
        {
            get { return _varUrl; }
            set { _varUrl = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable varIconIndex.
        /// </summary>
        [TestVariable("220c71d3-f6f0-48d8-a2ad-323a55b0a9b9")]
        public string varIconIndex
        {
            get { return repo.varIconIndex; }
            set { repo.varIconIndex = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable varExpires.
        /// </summary>
        [TestVariable("c0b28b27-2dd6-4fcc-8f39-b2e65c7de520")]
        public string varExpires
        {
            get { return repo.varExpires; }
            set { repo.varExpires = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable varTitle.
        /// </summary>
        [TestVariable("35c593c6-b59d-4ef7-b66f-07ee34e5c763")]
        public string varTitle
        {
            get { return repo.varTitle; }
            set { repo.varTitle = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainForm.Edit' at 25;13.", repo.MainForm.EditInfo, new RecordItemIndex(0));
            repo.MainForm.Edit.Click("25;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'KeePass.AddEntry' at 49;10.", repo.KeePass.AddEntryInfo, new RecordItemIndex(1));
            repo.KeePass.AddEntry.Click("49;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PwEntryForm.MTabEntry.Text' at 42;7.", repo.PwEntryForm.MTabEntry.TextInfo, new RecordItemIndex(2));
            repo.PwEntryForm.MTabEntry.Text.Click("42;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varTitle' with focus on 'PwEntryForm.MTabEntry.Text'.", repo.PwEntryForm.MTabEntry.TextInfo, new RecordItemIndex(3));
            repo.PwEntryForm.MTabEntry.Text.PressKeys(varTitle);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PwEntryForm.MTabEntry.MBtnIcon' at 12;8.", repo.PwEntryForm.MTabEntry.MBtnIconInfo, new RecordItemIndex(4));
            repo.PwEntryForm.MTabEntry.MBtnIcon.Click("12;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Invoke Action", "Invoking Select() on item 'IconPickerForm.ListItem1'.", repo.IconPickerForm.ListItem1Info, new RecordItemIndex(5));
            repo.IconPickerForm.ListItem1.Select();
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'IconPickerForm.ListItem1' at 16;6.", repo.IconPickerForm.ListItem1Info, new RecordItemIndex(6));
            //repo.IconPickerForm.ListItem1.Click("16;6");
            //Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'IconPickerForm.MBtnOK' at 34;10.", repo.IconPickerForm.MBtnOKInfo, new RecordItemIndex(7));
            repo.IconPickerForm.MBtnOK.Click("34;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PwEntryForm.MTabEntry.UserName' at 207;5.", repo.PwEntryForm.MTabEntry.UserNameInfo, new RecordItemIndex(8));
            repo.PwEntryForm.MTabEntry.UserName.Click("207;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varUsername' with focus on 'PwEntryForm.MTabEntry.UserName'.", repo.PwEntryForm.MTabEntry.UserNameInfo, new RecordItemIndex(9));
            repo.PwEntryForm.MTabEntry.UserName.PressKeys(varUsername);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PwEntryForm.MTabEntry.Password' at 204;5.", repo.PwEntryForm.MTabEntry.PasswordInfo, new RecordItemIndex(10));
            repo.PwEntryForm.MTabEntry.Password.Click("204;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'PwEntryForm.MTabEntry.Password' at 201;8.", repo.PwEntryForm.MTabEntry.PasswordInfo, new RecordItemIndex(11));
            repo.PwEntryForm.MTabEntry.Password.Click(System.Windows.Forms.MouseButtons.Right, "201;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'KeePass.SelectAll' at 47;8.", repo.KeePass.SelectAllInfo, new RecordItemIndex(12));
            repo.KeePass.SelectAll.Click("47;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varPassword' with focus on 'PwEntryForm.MTabEntry.Password'.", repo.PwEntryForm.MTabEntry.PasswordInfo, new RecordItemIndex(13));
            repo.PwEntryForm.MTabEntry.Password.PressKeys(varPassword);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PwEntryForm.MTabEntry.Repeat' at 231;8.", repo.PwEntryForm.MTabEntry.RepeatInfo, new RecordItemIndex(14));
            repo.PwEntryForm.MTabEntry.Repeat.Click("231;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'PwEntryForm.MTabEntry.Repeat' at 231;8.", repo.PwEntryForm.MTabEntry.RepeatInfo, new RecordItemIndex(15));
            repo.PwEntryForm.MTabEntry.Repeat.Click(System.Windows.Forms.MouseButtons.Right, "231;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'KeePass.SelectAll' at 39;11.", repo.KeePass.SelectAllInfo, new RecordItemIndex(16));
            repo.KeePass.SelectAll.Click("39;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varPassword' with focus on 'PwEntryForm.MTabEntry.Repeat'.", repo.PwEntryForm.MTabEntry.RepeatInfo, new RecordItemIndex(17));
            repo.PwEntryForm.MTabEntry.Repeat.PressKeys(varPassword);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PwEntryForm.MTabEntry.URL' at 122;5.", repo.PwEntryForm.MTabEntry.URLInfo, new RecordItemIndex(18));
            repo.PwEntryForm.MTabEntry.URL.Click("122;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varUrl' with focus on 'PwEntryForm.MTabEntry.URL'.", repo.PwEntryForm.MTabEntry.URLInfo, new RecordItemIndex(19));
            repo.PwEntryForm.MTabEntry.URL.PressKeys(varUrl);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PwEntryForm.MTabEntry.MBtnStandardExpires' at 19;8.", repo.PwEntryForm.MTabEntry.MBtnStandardExpiresInfo, new RecordItemIndex(20));
            repo.PwEntryForm.MTabEntry.MBtnStandardExpires.Click("19;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'KeePass.MI_Expires' at 66;12.", repo.KeePass.MI_ExpiresInfo, new RecordItemIndex(21));
            repo.KeePass.MI_Expires.Click("66;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PwEntryForm.MBtnOK' at 63;14.", repo.PwEntryForm.MBtnOKInfo, new RecordItemIndex(22));
            repo.PwEntryForm.MBtnOK.Click("63;14");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
