///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace OnlineTutorial
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the OnlineTutorialRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
    [RepositoryFolder("aeacc831-8803-4a38-9cb3-f59c7ffc5e1e")]
    public partial class OnlineTutorialRepository : RepoGenBaseFolder
    {
        static OnlineTutorialRepository instance = new OnlineTutorialRepository();

        /// <summary>
        /// Gets the singleton class instance representing the OnlineTutorialRepository element repository.
        /// </summary>
        [RepositoryFolder("aeacc831-8803-4a38-9cb3-f59c7ffc5e1e")]
        public static OnlineTutorialRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public OnlineTutorialRepository() 
            : base("OnlineTutorialRepository", "/", null, 0, false, "aeacc831-8803-4a38-9cb3-f59c7ffc5e1e", ".\\RepositoryImages\\OnlineTutorialRepositoryaeacc831.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("aeacc831-8803-4a38-9cb3-f59c7ffc5e1e")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
    public partial class OnlineTutorialRepositoryFolders
    {
    }
#pragma warning restore 0436
}