///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace OnlineTutorial
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The StartSUT recording.
    /// </summary>
    [TestModule("5ef16dae-0ec3-43d7-a5eb-af6815b6a486", ModuleType.Recording, 1)]
    public partial class StartSUT : ITestModule
    {
        /// <summary>
        /// Holds an instance of the OnlineTutorialRepository repository.
        /// </summary>
        public static OnlineTutorialRepository repo = OnlineTutorialRepository.Instance;

        static StartSUT instance = new StartSUT();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public StartSUT()
        {
            varApplicationPath = "C:\\Users\\JMPSUser\\Documents\\Ranorex\\RanorexStudio Projects\\OnlineTutorial\\OnlineTutorial\\KeePass\\KeePass.exe";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static StartSUT Instance
        {
            get { return instance; }
        }

#region Variables

        string _varApplicationPath;

        /// <summary>
        /// Gets or sets the value of variable varApplicationPath.
        /// </summary>
        [TestVariable("ad967cff-0cb1-4ace-8835-e56794cd44aa")]
        public string varApplicationPath
        {
            get { return _varApplicationPath; }
            set { _varApplicationPath = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Run application 'C:\\Users\\JMPSUser\\Documents\\Ranorex\\RanorexStudio Projects\\OnlineTutorial\\OnlineTutorial\\KeePass\\KeePass.exe' with arguments '' in normal mode.", new RecordItemIndex(0));
            Host.Local.RunApplication("C:\\Users\\JMPSUser\\Documents\\Ranorex\\RanorexStudio Projects\\OnlineTutorial\\OnlineTutorial\\KeePass\\KeePass.exe", "", "C:\\Users\\JMPSUser\\Documents\\Ranorex\\RanorexStudio Projects\\OnlineTutorial\\OnlineTutorial\\KeePass", false);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
